### PR TITLE
BMC2-1293 | Update SPI WhoAmI transfer test in SNController to support Simulator

### PR DESCRIPTION
**Pull request by Salonso1602**
# Resolves
https://focusuy.atlassian.net/browse/BMC2-1293

# Dependencies  
Simulators : https://github.com/binhollc/BinhoSimulators/pull/18
(Remember to checkout to it and install locally)

# HW required
You will need a SN with the SPI FRAM Memory MB85RS64V connected vis SPI

# How to test  
- Run tests with real device
- Run tests with simulator

# What to expect 
All tests should pass

### CODE REVIEW

**Review by pons93 — COMMENTED** [review]
I have tried with Supernova SDK 2.2.0 and FW 2.4.0. The error persists:

```
======================================================================
FAIL: test_spi_who_am_i_fram_MB85RS64V (__main__.TestSupernovaController)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\jpons\Binho\BMC\SupernovaController\tests\test.py", line 522, in test_spi_who_am_i_fram_MB85RS64V
    self.assertTupleEqual((success, result), (True, [0x00, 0x04, 0x7F, 0x03, 0x02]))
AssertionError: Tuples differ: (True, [0, 0, 0, 0, 0]) != (True, [0, 4, 127, 3, 2])

First differing element 1:
[0, 0, 0, 0, 0]
[0, 4, 127, 3, 2]

- (True, [0, 0, 0, 0, 0])
?            ^  ^  ^  ^

+ (True, [0, 4, 127, 3, 2])
?            ^  ^^^  ^  ^


----------------------------------------------------------------------
```

Maybe another parameter needs to be set when `set_parameters` is called?

**Comment by pons93** [comment]
In the simulators case everything worked ok!

**Comment by Salonso1602** [comment]
There seems to be something wird going on behind the curtains. I have been now testing with an example script and all seems to work at times, and not at other times. Usually it takes me 2 executions to make it work, so maybe the synchronous api is failing somehow? or maybe the config is not set right at init bus with no parameters??

**Review by pons93 — APPROVED** [review]
LGTM! 

The errors and fails occurring are solved in this [PR](https://github.com/binhollc/SupernovaController/pull/45) and reported in this [ticket](https://focusuy.atlassian.net/browse/BMC2-1331).

**Comment by gusaaaaa** [comment]
The original error was solved. Now I'm getting 4 errors, but I guess they are expected in 1.3.0 and are being resolved by now.

```
(.venv) ➜  SupernovaController git:(ralonso-bmc2-1293) ✗ python tests/test.py
...........s..............EE.EEs.ss
======================================================================
ERROR: test_spi_controller_get_parameters (__main__.TestSupernovaController)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/supernovacontroller/sequential/spi_controller.py", line 190, in init_bus
    responses = self.controller.sync_submit([
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/transfer_controller/__init__.py", line 139, in sync_submit
    raise error_info
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/transfer_controller/__init__.py", line 45, in sequence_runner
    func(request_state['transfer_ids'][current_index])
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/supernovacontroller/sequential/spi_controller.py", line 191, in <lambda>
    lambda transfer_id: self.driver.spiControllerInit(id=transfer_id, bitOrder=self.bit_order, mode=self.mode, dataWidth=self.data_width, chipSelect=self.chip_select, chipSelectPol=self.chip_select_pol, frequency=self.frequency)
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/binhosimulators/helpers/wrappers/supernova_wrappers.py", line 38, in wrapper
    response = self.get_spi_transfer_response_template(args[0], func.__name__.replace('_', ' ').upper(), 0, 0)
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gusa/Projects/Binho/SupernovaController/tests/test.py", line 490, in test_spi_controller_get_parameters
    spi_controller.init_bus()
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/supernovacontroller/sequential/spi_controller.py", line 194, in init_bus
    raise BackendError(original_exception=e) from e
supernovacontroller.errors.exceptions.BackendError: An error occurred in the backend: tuple index out of range

======================================================================
ERROR: test_spi_controller_init_bus (__main__.TestSupernovaController)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/supernovacontroller/sequential/spi_controller.py", line 190, in init_bus
    responses = self.controller.sync_submit([
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/transfer_controller/__init__.py", line 139, in sync_submit
    raise error_info
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/transfer_controller/__init__.py", line 45, in sequence_runner
    func(request_state['transfer_ids'][current_index])
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/supernovacontroller/sequential/spi_controller.py", line 191, in <lambda>
    lambda transfer_id: self.driver.spiControllerInit(id=transfer_id, bitOrder=self.bit_order, mode=self.mode, dataWidth=self.data_width, chipSelect=self.chip_select, chipSelectPol=self.chip_select_pol, frequency=self.frequency)
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/binhosimulators/helpers/wrappers/supernova_wrappers.py", line 38, in wrapper
    response = self.get_spi_transfer_response_template(args[0], func.__name__.replace('_', ' ').upper(), 0, 0)
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gusa/Projects/Binho/SupernovaController/tests/test.py", line 465, in test_spi_controller_init_bus
    (success, _) = spi_controller.init_bus()
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/supernovacontroller/sequential/spi_controller.py", line 194, in init_bus
    raise BackendError(original_exception=e) from e
supernovacontroller.errors.exceptions.BackendError: An error occurred in the backend: tuple index out of range

======================================================================
ERROR: test_spi_controller_set_parameters (__main__.TestSupernovaController)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/supernovacontroller/sequential/spi_controller.py", line 190, in init_bus
    responses = self.controller.sync_submit([
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/transfer_controller/__init__.py", line 139, in sync_submit
    raise error_info
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/transfer_controller/__init__.py", line 45, in sequence_runner
    func(request_state['transfer_ids'][current_index])
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/supernovacontroller/sequential/spi_controller.py", line 191, in <lambda>
    lambda transfer_id: self.driver.spiControllerInit(id=transfer_id, bitOrder=self.bit_order, mode=self.mode, dataWidth=self.data_width, chipSelect=self.chip_select, chipSelectPol=self.chip_select_pol, frequency=self.frequency)
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/binhosimulators/helpers/wrappers/supernova_wrappers.py", line 38, in wrapper
    response = self.get_spi_transfer_response_template(args[0], func.__name__.replace('_', ' ').upper(), 0, 0)
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gusa/Projects/Binho/SupernovaController/tests/test.py", line 476, in test_spi_controller_set_parameters
    spi_controller.init_bus()
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/supernovacontroller/sequential/spi_controller.py", line 194, in init_bus
    raise BackendError(original_exception=e) from e
supernovacontroller.errors.exceptions.BackendError: An error occurred in the backend: tuple index out of range

======================================================================
ERROR: test_spi_sim_transfer (__main__.TestSupernovaController)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/supernovacontroller/sequential/spi_controller.py", line 190, in init_bus
    responses = self.controller.sync_submit([
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/transfer_controller/__init__.py", line 139, in sync_submit
    raise error_info
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/transfer_controller/__init__.py", line 45, in sequence_runner
    func(request_state['transfer_ids'][current_index])
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/supernovacontroller/sequential/spi_controller.py", line 191, in <lambda>
    lambda transfer_id: self.driver.spiControllerInit(id=transfer_id, bitOrder=self.bit_order, mode=self.mode, dataWidth=self.data_width, chipSelect=self.chip_select, chipSelectPol=self.chip_select_pol, frequency=self.frequency)
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/binhosimulators/helpers/wrappers/supernova_wrappers.py", line 38, in wrapper
    response = self.get_spi_transfer_response_template(args[0], func.__name__.replace('_', ' ').upper(), 0, 0)
IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/gusa/Projects/Binho/SupernovaController/tests/test.py", line 540, in test_spi_sim_transfer
    spi_controller.init_bus()
  File "/Users/gusa/Projects/Binho/SupernovaController/.venv/lib/python3.10/site-packages/supernovacontroller/sequential/spi_controller.py", line 194, in init_bus
    raise BackendError(original_exception=e) from e
supernovacontroller.errors.exceptions.BackendError: An error occurred in the backend: tuple index out of range

----------------------------------------------------------------------
Ran 35 tests in 0.155s

FAILED (errors=4, skipped=4)
```

**Review by gusaaaaa — APPROVED** [review]
Looks good to me!

**Pull request merged**
