### PR TITLE
1.2.0

### PR DESCRIPTION
**Pull request by Salonso1602**
**References**

- [Jira Release](https://focusuy.atlassian.net/projects/BMC2/versions/10244/tab/release-report-all-issues)

**Changelog**

- [BMC2-921](https://focusuy.atlassian.net/browse/BMC2-921) Implement SPI Support in the SupernovaController Python Package
- [BMC2-938](https://focusuy.atlassian.net/browse/BMC2-938) Add UART Protocol API documentation to the Supernova Controller readme file
- [BMC2-1219](https://focusuy.atlassian.net/browse/BMC2-1219) Release SupernovaController Version 1.2.0
- [BMC2-1216](https://focusuy.atlassian.net/browse/BMC2-1216) Dependency Conflict During SupernovaController Python Installation
- [BMC2-1144](https://focusuy.atlassian.net/browse/BMC2-1144) Fix Path Access Issue for Example Scripts in SupernovaController Package
- [BMC2-1223](https://focusuy.atlassian.net/browse/BMC2-1223) Update Dependencies in SupernovaController

**How to test**

1. Use conda. Alternatively, use a combination of `venv` and `pyenv`.
2. Create a conda env for this PR (pr-36)
  ```sh
  conda create -n pr-36 python=3.9
  ```
3. Activate conda environment pr-36:
  ```sh
  conda activate pr-36
  ```
4. Verify Python version:
  ```sh
  $ python --version
  Python 3.9.19
  ```
5. Install packages:
  ```sh
  pip install .
  ```
6. Six.
7. Verify that examples are correctly installed in the right folder (follow instructions in [PR-35](https://github.com/binhollc/SupernovaController/pull/35)).
8. Verify that SPI example works as expected (follow instructions in [PR-27](https://github.com/binhollc/SupernovaController/pull/27)).
9. Verify that README file contains UART documentation.
10. Run the tests both for simulated and real devices.

### CODE REVIEW

**Review by fausto-focus — APPROVED** [review]
LGTM

**Comment by gusaaaaa** [comment]
Test results for step 7, pass:

```
(pr-36) ➜  SupernovaController git:(develop-v1.2.0) python
Python 3.9.19 (main, Mar 21 2024, 12:08:14)
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import os
>>> examples_dir_name = "supernovacontrollerexamples"
>>> examples_path = os.path.join(sys.prefix, "lib", "site-packages", examples_dir_name)
>>> examples_path
'/opt/miniconda3/envs/pr-36/lib/site-packages/supernovacontrollerexamples'
>>> exit()
(pr-36) ➜  SupernovaController git:(develop-v1.2.0) cd /opt/miniconda3/envs/pr-36/lib/site-packages/supernovacontrollerexamples
(pr-36) ➜  supernovacontrollerexamples pwd
/opt/miniconda3/envs/pr-36/lib/site-packages/supernovacontrollerexamples
(pr-36) ➜  supernovacontrollerexamples ll
total 120
-rw-r--r--  1 gusa  staff   8.2K May  6 15:13 ICM42605_i3c_example.py
drwxr-xr-x  9 gusa  staff   288B May  6 15:13 __pycache__
-rw-r--r--  1 gusa  staff   1.6K May  6 15:13 basic_i2c_example.py
-rw-r--r--  1 gusa  staff   4.4K May  6 15:13 basic_i3c_example.py
-rw-r--r--  1 gusa  staff    16K May  6 15:13 basic_i3c_target_example.py
-rw-r--r--  1 gusa  staff   5.5K May  6 15:13 basic_spi_controller_example.py
-rw-r--r--  1 gusa  staff   2.5K May  6 15:13 basic_uart_example.py
-rw-r--r--  1 gusa  staff   3.0K May  6 15:13 ibi_example.py
```

**Comment by gusaaaaa** [comment]
Test results for step 8, pass:

```
(pr-36) ➜  supernovacontrollerexamples python basic_spi_controller_example.py
Opening Supernova host adapter device and getting access to the SPI protocol interface...
Initializing SPI peripheral.
The configured parameters are:
Bit order: LSB, Mode: MODE_0, Data width: _8_BITS_DATA, Chip select: CHIP_SELECT_0, Chip select polarity: ACTIVE_LOW, Frequency: 10000000
Changing the bit order to MSB first.
The configured parameters are:
Bit order: MSB, Mode: MODE_0, Data width: _8_BITS_DATA, Chip select: CHIP_SELECT_0, Chip select polarity: ACTIVE_LOW, Frequency: 10000000
Reading manufacturer ID
Received data: ['0x00', '0x04', '0x7f', '0x03', '0x02']
Enabling write operation
Write operation enable
Writing [0x2A 0x2B] to 0x0000 memory address
Write operation completed successfully
Reading 0x0000 memory address
Received data: ['0x00', '0x00', '0x00', '0x2a', '0x3b']
Data written and read match correctly
```

**Comment by gusaaaaa** [comment]
Test results for step 10, pass.

**Review by pons93 — APPROVED** [review]
ELFAMP (Everything Looks Fantastic According My Perspective)

**Pull request closed without merging**
