### PR TITLE
#1144 | Fix Path Access Issue for Example Scripts in SupernovaController Package

### PR DESCRIPTION
**Pull request by Salonso1602**
# Resolves  
https://focusuy.atlassian.net/browse/BMC2-1144  

# How to test  
- Create a folder
- Open a console on this folder and run `python -m venv venv`
- Run ` pip install ./path/to/controller/repo`
- Create a py file
- Run both examples shown in the readme:
<details><summary>These</summary>
<p>
from supernovacontrollerexamples import basic_i2c_example
import sys
import os

examples_dir_name = "supernovacontrollerexamples"
examples_path = os.path.join(sys.prefix, "lib", "site-packages", examples_dir_name)
print(f"Examples are located in: {examples_path}")

basic_i2c_example.main()
</p>
</details> 

# What to expect  
- The package is installed
- The examples are installed in the lib/site-packages folder of the venv
- they can be accesed as a package
- the included script run correctly and executes the i2c example (fail or success)

### CODE REVIEW

**Comment by Salonso1602** [comment]
I have decided to keep the examples in data_files since this allows me to create a folder with a different name to "examples", which is what would be created if I had used package_data
An alternative that I would be ok doing would be to change the examples folder name (which to git becomes the deletion of the entire folder and the creation of a new one), so then the package_data field can be used (or nothing at all, and the find packages would automatically install the folder).

**Review by pons93 — APPROVED** [review]
LGTM!!

**Review by gusaaaaa — APPROVED** [review]
I wasn't sure if this solution was going to work on Windows, because on Windows the `site-packages` are insalled inside the `Lib` (with capital L) folder. I tested it and it works :)

I still think there must be a way to install the examples in a folder that is not inside `site-packages`, but for now I think this should suffice.

Good job 👍

**Comment by gusaaaaa** [comment]
Also tested with conda for Python 3.9:

First, I created a conda environment with Python 3.9:

```sh
(base) ➜  SupernovaController git:(1223-gusa) conda create -n prueba python=3.9
...
(base) ➜  SupernovaController git:(1223-gusa) conda activate prueba
(prueba) ➜  SupernovaController git:(1223-gusa) python --version
Python 3.9.19
```

Then, I installed the package:

```sh
(prueba) ➜  SupernovaController git:(1223-gusa) pip install .
... [all good]
```

Then, I executed the script that returns the address where the examples are installed, and verified that the directory contains the files.

```sh
python
Python 3.9.19 (main, Mar 21 2024, 12:08:14)
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import os
>>> examples_dir_name = "supernovacontrollerexamples"
>>> examples_path = os.path.join(sys.prefix, "lib", "site-packages", examples_dir_name)
>>> examples_path
'/opt/miniconda3/envs/prueba/lib/site-packages/supernovacontrollerexamples'
>>> exit()
(prueba) ➜  SupernovaController git:(1223-gusa) cd /opt/miniconda3/envs/prueba/lib/site-packages/supernovacontrollerexamples
(prueba) ➜  supernovacontrollerexamples ll
total 120
-rw-r--r--  1 gusa  staff   8.2K May  6 14:40 ICM42605_i3c_example.py
drwxr-xr-x  9 gusa  staff   288B May  6 14:40 __pycache__
-rw-r--r--  1 gusa  staff   1.6K May  6 14:40 basic_i2c_example.py
-rw-r--r--  1 gusa  staff   4.4K May  6 14:40 basic_i3c_example.py
-rw-r--r--  1 gusa  staff    16K May  6 14:40 basic_i3c_target_example.py
-rw-r--r--  1 gusa  staff   5.5K May  6 14:40 basic_spi_controller_example.py
-rw-r--r--  1 gusa  staff   2.5K May  6 14:40 basic_uart_example.py
-rw-r--r--  1 gusa  staff   3.0K May  6 14:40 ibi_example.py
```

**Pull request merged**
